// This file is @generated by prost-build.
/// WorkerEvent is the envelope that wraps all event types.
///
/// Every event published to Kafka uses this wrapper, which provides:
/// - Unique identification (event_id)
/// - Type discrimination (event_type)
/// - Versioning for schema evolution (event_version)
/// - Timestamp for ordering and debugging (timestamp)
/// - Source attribution (source)
/// - The actual event payload (payload oneof)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WorkerEvent {
    /// Unique event identifier.
    /// Format: UUID v7 (time-ordered) for natural chronological sorting.
    /// Example: "01912345-6789-7abc-def0-123456789abc"
    #[prost(string, tag = "1")]
    pub event_id: ::prost::alloc::string::String,
    /// Event type discriminator for routing and filtering.
    /// Values: "sync.started", "sync.progress", "sync.completed", "sync.failed"
    #[prost(string, tag = "2")]
    pub event_type: ::prost::alloc::string::String,
    /// Schema version for forward compatibility.
    /// Consumers should handle unknown fields gracefully.
    /// Current version: "1.0"
    #[prost(string, tag = "3")]
    pub event_version: ::prost::alloc::string::String,
    /// Event timestamp in RFC 3339 format.
    /// Example: "2024-01-15T10:30:00.123Z"
    #[prost(string, tag = "4")]
    pub timestamp: ::prost::alloc::string::String,
    /// Source metadata identifying the worker that emitted this event.
    #[prost(message, optional, tag = "5")]
    pub source: ::core::option::Option<EventSource>,
    /// Event payload - exactly one of the specific event types.
    /// Use event_type field to determine which payload is present.
    #[prost(oneof = "worker_event::Payload", tags = "10, 11, 12, 13")]
    pub payload: ::core::option::Option<worker_event::Payload>,
}
/// Nested message and enum types in `WorkerEvent`.
pub mod worker_event {
    /// Event payload - exactly one of the specific event types.
    /// Use event_type field to determine which payload is present.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "10")]
        SyncStarted(super::SyncStarted),
        #[prost(message, tag = "11")]
        SyncProgress(super::SyncProgress),
        #[prost(message, tag = "12")]
        SyncCompleted(super::SyncCompleted),
        #[prost(message, tag = "13")]
        SyncFailed(super::SyncFailed),
    }
}
/// EventSource identifies the origin of an event.
///
/// Used for debugging, tracing, and correlating events across
/// a distributed worker fleet.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EventSource {
    /// Unique identifier of the worker instance.
    /// Format: Typically a UUID or hostname-based identifier.
    /// Example: "worker-abc123" or "01912345-6789-7abc-def0-123456789abc"
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
}
/// DatasetInfo uniquely identifies a dataset being synced.
///
/// The combination of (namespace, name, manifest_hash) forms a unique
/// reference to a specific version of a dataset definition.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DatasetInfo {
    /// Dataset namespace (organization or project scope).
    /// Example: "ethereum", "polygon", "my-org"
    #[prost(string, tag = "1")]
    pub namespace: ::prost::alloc::string::String,
    /// Dataset name within the namespace.
    /// Example: "mainnet", "transactions", "blocks"
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Hash of the dataset manifest for version identification.
    /// Format: 64-character hex string (SHA-256).
    /// Example: "a1b2c3d4e5f6..."
    #[prost(string, tag = "3")]
    pub manifest_hash: ::prost::alloc::string::String,
}
/// ProgressInfo contains detailed progress metrics for a sync job.
///
/// Used within SyncProgress events to report incremental progress.
/// Some fields are optional for continuous (unbounded) sync jobs.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProgressInfo {
    /// Starting block number of the sync job.
    /// This is the first block the job will process.
    #[prost(uint64, tag = "1")]
    pub start_block: u64,
    /// Current block number being processed.
    /// Increases as the job progresses through the block range.
    #[prost(uint64, tag = "2")]
    pub current_block: u64,
    /// Target end block number (bounded jobs only).
    /// Not set for continuous/live sync jobs that follow chain head.
    /// Consumers can calculate percentage as: (current_block - start_block) / (end_block - start_block) * 100
    #[prost(uint64, optional, tag = "3")]
    pub end_block: ::core::option::Option<u64>,
    /// Number of parquet files written so far.
    /// Useful for monitoring output volume.
    #[prost(uint64, tag = "5")]
    pub files_count: u64,
    /// Total bytes written across all files.
    /// Useful for monitoring storage consumption.
    #[prost(uint64, tag = "6")]
    pub total_size_bytes: u64,
}
/// SyncStarted is emitted when a sync job begins processing a table.
///
/// Event type: "sync.started"
///
/// This event is emitted once per table when the job starts.
/// For multi-table datasets, multiple SyncStarted events are emitted.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SyncStarted {
    /// Database ID of the job.
    /// Can be used to correlate with job records in the metadata database.
    #[prost(int64, tag = "1")]
    pub job_id: i64,
    /// Dataset being synced.
    #[prost(message, optional, tag = "2")]
    pub dataset: ::core::option::Option<DatasetInfo>,
    /// Name of the table being synced.
    /// Example: "blocks", "transactions", "logs"
    #[prost(string, tag = "3")]
    pub table_name: ::prost::alloc::string::String,
    /// Starting block number (if known at job start).
    /// May not be set if the job determines this dynamically.
    #[prost(uint64, optional, tag = "4")]
    pub start_block: ::core::option::Option<u64>,
    /// Target end block number (if this is a bounded job).
    /// Not set for continuous/live sync jobs.
    #[prost(uint64, optional, tag = "5")]
    pub end_block: ::core::option::Option<u64>,
}
/// SyncProgress is emitted periodically during sync job execution.
///
/// Event type: "sync.progress"
///
/// Emission frequency is time-based (configurable interval, default 10s).
/// Events are only emitted when there is new progress to report.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SyncProgress {
    /// Database ID of the job.
    #[prost(int64, tag = "1")]
    pub job_id: i64,
    /// Dataset being synced.
    #[prost(message, optional, tag = "2")]
    pub dataset: ::core::option::Option<DatasetInfo>,
    /// Name of the table being synced.
    #[prost(string, tag = "3")]
    pub table_name: ::prost::alloc::string::String,
    /// Detailed progress metrics.
    #[prost(message, optional, tag = "4")]
    pub progress: ::core::option::Option<ProgressInfo>,
}
/// SyncCompleted is emitted when a sync job finishes successfully.
///
/// Event type: "sync.completed"
///
/// This event indicates the job processed all blocks in its range
/// without errors. For continuous jobs, this is emitted when the
/// job is gracefully stopped.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SyncCompleted {
    /// Database ID of the job.
    #[prost(int64, tag = "1")]
    pub job_id: i64,
    /// Dataset that was synced.
    #[prost(message, optional, tag = "2")]
    pub dataset: ::core::option::Option<DatasetInfo>,
    /// Name of the table that was synced.
    #[prost(string, tag = "3")]
    pub table_name: ::prost::alloc::string::String,
    /// Last block number that was successfully processed.
    #[prost(uint64, tag = "4")]
    pub final_block: u64,
    /// Total job duration in milliseconds.
    /// Measured from job start to completion.
    #[prost(uint64, tag = "5")]
    pub duration_millis: u64,
}
/// SyncFailed is emitted when a sync job fails.
///
/// Event type: "sync.failed"
///
/// This event indicates the job encountered an unrecoverable error.
/// The job may be retried depending on the error type and retry policy.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SyncFailed {
    /// Database ID of the job.
    #[prost(int64, tag = "1")]
    pub job_id: i64,
    /// Dataset that failed to sync.
    #[prost(message, optional, tag = "2")]
    pub dataset: ::core::option::Option<DatasetInfo>,
    /// Name of the table that failed.
    #[prost(string, tag = "3")]
    pub table_name: ::prost::alloc::string::String,
    /// Human-readable error message.
    /// Example: "Failed to connect to RPC endpoint"
    #[prost(string, tag = "4")]
    pub error_message: ::prost::alloc::string::String,
    /// Error type classification (optional).
    /// Used for error categorization and retry decisions.
    /// Examples: "NetworkError", "RateLimitError", "SchemaError"
    #[prost(string, optional, tag = "5")]
    pub error_type: ::core::option::Option<::prost::alloc::string::String>,
}
