{
 "title": "dump-metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total rows dumped",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(raw_dataset_rows_dumped_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total bytes written",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(raw_dataset_bytes_written_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total files written",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raw_dataset_files_written_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rows/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(raw_dataset_rows_dumped_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "rate(raw_dataset_bytes_written_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Files/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "rate(raw_dataset_files_written_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "otelcol_process_uptime_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "otelcol_process_memory_rss", "legendFormat": "__auto" }
   ]
  }
 ]
}