-- =============================================================
-- Migration: Job Ledger — append-only job event log
-- =============================================================
-- Introduces the job_events table to replace job_attempts:
--   1. job_events    — append-only lifecycle event log
--   2. Backfill      — seeds one event per existing job
--   3. Foreign key   — links job_events to jobs
--   4. Update existing jobs to statuses
--   5. Drop job_attempts table
-- =============================================================

-- -------------------------------------------------------------
-- 1. Create job_events table
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS job_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT timezone('UTC', now()),
    job_id      BIGINT      NOT NULL,  -- FK to jobs(id)
    node_id     TEXT        NOT NULL,
    event_type  TEXT        NOT NULL,
    detail      JSONB
);

CREATE INDEX IF NOT EXISTS idx_job_events_job_id_id ON job_events (job_id, id);

-- -------------------------------------------------------------
-- 2. Backfill job_events from existing jobs (one event per job)
-- -------------------------------------------------------------
INSERT INTO job_events (created_at, job_id, node_id, event_type, detail)
SELECT
    created_at,
    id,
    node_id,
    CASE status
        WHEN 'SCHEDULED'          THEN 'SCHEDULED'
        WHEN 'RUNNING'            THEN 'RUNNING'
        WHEN 'COMPLETED'          THEN 'COMPLETED'
        WHEN 'STOPPED'            THEN 'STOPPED'
        WHEN 'FAILED_RECOVERABLE' THEN 'ERROR'
        WHEN 'FAILED_FATAL'       THEN 'FATAL'
        ELSE status
    END,
    NULL
FROM jobs
ORDER BY id;

-- -------------------------------------------------------------
-- 3. Add foreign key constraint
-- -------------------------------------------------------------
ALTER TABLE job_events
    ADD CONSTRAINT fk_job_events_job_id
    FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;

-- -------------------------------------------------------------
-- 4. Update existing jobs to statuses
-- -------------------------------------------------------------

UPDATE jobs
SET status = CASE status
    WHEN 'FAILED_RECOVERABLE' THEN 'ERROR'
    WHEN 'FAILED_FATAL'       THEN 'FATAL'
END
WHERE status = ANY(ARRAY['FAILED_RECOVERABLE', 'FAILED_FATAL']);

-- -------------------------------------------------------------
-- 5. Drop job_attempts table
-- -------------------------------------------------------------
DROP TABLE IF EXISTS job_attempts;