-- Create redump_requests table for tracking block range re-extraction requests
-- These requests are picked up by active dump jobs to re-extract corrupted segments

CREATE TABLE IF NOT EXISTS redump_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Dataset identification (matches job descriptor)
    dataset_namespace TEXT NOT NULL,
    dataset_name TEXT NOT NULL,
    manifest_hash TEXT NOT NULL,

    -- Requested block range (before segment expansion)
    start_block BIGINT NOT NULL,
    end_block BIGINT NOT NULL,

    -- Metadata
    created_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),

    -- Validate block range
    CONSTRAINT valid_block_range CHECK (start_block <= end_block)
);

-- Index for efficient lookup by dataset
CREATE INDEX IF NOT EXISTS idx_redump_requests_dataset
ON redump_requests (dataset_namespace, dataset_name, manifest_hash);

-- Unique constraint to prevent duplicate requests for same dataset and range
CREATE UNIQUE INDEX IF NOT EXISTS idx_redump_requests_unique
ON redump_requests (dataset_namespace, dataset_name, manifest_hash, start_block, end_block);
