// This file is @generated by prost-build.
/// Event envelope - common wrapper for all events
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkerEvent {
    /// Unique event identifier (UUID v7 for time-ordering)
    #[prost(string, tag = "1")]
    pub event_id: ::prost::alloc::string::String,
    /// Event type discriminator (e.g., "sync.started", "sync.progress")
    #[prost(string, tag = "2")]
    pub event_type: ::prost::alloc::string::String,
    /// Schema version for forward compatibility
    #[prost(string, tag = "3")]
    pub event_version: ::prost::alloc::string::String,
    /// Event timestamp (RFC 3339)
    #[prost(string, tag = "4")]
    pub timestamp: ::prost::alloc::string::String,
    /// Event source metadata
    #[prost(message, optional, tag = "5")]
    pub source: ::core::option::Option<EventSource>,
    /// Event payload (one of the specific event types)
    #[prost(oneof = "worker_event::Payload", tags = "10, 11, 12, 13")]
    pub payload: ::core::option::Option<worker_event::Payload>,
}
/// Nested message and enum types in `WorkerEvent`.
pub mod worker_event {
    /// Event payload (one of the specific event types)
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "10")]
        SyncStarted(super::SyncStarted),
        #[prost(message, tag = "11")]
        SyncProgress(super::SyncProgress),
        #[prost(message, tag = "12")]
        SyncCompleted(super::SyncCompleted),
        #[prost(message, tag = "13")]
        SyncFailed(super::SyncFailed),
    }
}
/// Source metadata for event tracing
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventSource {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
}
/// Dataset identifier
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DatasetInfo {
    #[prost(string, tag = "1")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub manifest_hash: ::prost::alloc::string::String,
}
/// Sync progress information
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ProgressInfo {
    #[prost(uint64, tag = "1")]
    pub start_block: u64,
    #[prost(uint64, tag = "2")]
    pub current_block: u64,
    /// Not set in continuous mode
    #[prost(uint64, optional, tag = "3")]
    pub end_block: ::core::option::Option<u64>,
    /// Not set in continuous mode
    #[prost(uint32, optional, tag = "4")]
    pub percentage: ::core::option::Option<u32>,
    #[prost(uint64, tag = "5")]
    pub files_count: u64,
    #[prost(uint64, tag = "6")]
    pub total_size_bytes: u64,
}
/// Event: Sync job started
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncStarted {
    #[prost(int64, tag = "1")]
    pub job_id: i64,
    #[prost(message, optional, tag = "2")]
    pub dataset: ::core::option::Option<DatasetInfo>,
    #[prost(string, tag = "3")]
    pub table_name: ::prost::alloc::string::String,
    #[prost(uint64, optional, tag = "4")]
    pub start_block: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "5")]
    pub end_block: ::core::option::Option<u64>,
}
/// Event: Sync progress update
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncProgress {
    #[prost(int64, tag = "1")]
    pub job_id: i64,
    #[prost(message, optional, tag = "2")]
    pub dataset: ::core::option::Option<DatasetInfo>,
    #[prost(string, tag = "3")]
    pub table_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub progress: ::core::option::Option<ProgressInfo>,
}
/// Event: Sync job completed successfully
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncCompleted {
    #[prost(int64, tag = "1")]
    pub job_id: i64,
    #[prost(message, optional, tag = "2")]
    pub dataset: ::core::option::Option<DatasetInfo>,
    #[prost(string, tag = "3")]
    pub table_name: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub final_block: u64,
    #[prost(uint64, tag = "5")]
    pub duration_millis: u64,
}
/// Event: Sync job failed
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncFailed {
    #[prost(int64, tag = "1")]
    pub job_id: i64,
    #[prost(message, optional, tag = "2")]
    pub dataset: ::core::option::Option<DatasetInfo>,
    #[prost(string, tag = "3")]
    pub table_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "5")]
    pub error_type: ::core::option::Option<::prost::alloc::string::String>,
}
