/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as DemoTanstackQueryRouteImport } from "./routes/demo.tanstack-query"
import { Route as DemoTableRouteImport } from "./routes/demo.table"
import { Route as DemoQueryableEventsRouteImport } from "./routes/demo.queryable-events"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: "/demo/tanstack-query",
  path: "/demo/tanstack-query",
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: "/demo/table",
  path: "/demo/table",
  getParentRoute: () => rootRouteImport,
} as any)
const DemoQueryableEventsRoute = DemoQueryableEventsRouteImport.update({
  id: "/demo/queryable-events",
  path: "/demo/queryable-events",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/demo/queryable-events": typeof DemoQueryableEventsRoute
  "/demo/table": typeof DemoTableRoute
  "/demo/tanstack-query": typeof DemoTanstackQueryRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/demo/queryable-events": typeof DemoQueryableEventsRoute
  "/demo/table": typeof DemoTableRoute
  "/demo/tanstack-query": typeof DemoTanstackQueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/demo/queryable-events": typeof DemoQueryableEventsRoute
  "/demo/table": typeof DemoTableRoute
  "/demo/tanstack-query": typeof DemoTanstackQueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/demo/queryable-events"
    | "/demo/table"
    | "/demo/tanstack-query"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/demo/queryable-events" | "/demo/table" | "/demo/tanstack-query"
  id:
    | "__root__"
    | "/"
    | "/demo/queryable-events"
    | "/demo/table"
    | "/demo/tanstack-query"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoQueryableEventsRoute: typeof DemoQueryableEventsRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/demo/tanstack-query": {
      id: "/demo/tanstack-query"
      path: "/demo/tanstack-query"
      fullPath: "/demo/tanstack-query"
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/demo/table": {
      id: "/demo/table"
      path: "/demo/table"
      fullPath: "/demo/table"
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/demo/queryable-events": {
      id: "/demo/queryable-events"
      path: "/demo/queryable-events"
      fullPath: "/demo/queryable-events"
      preLoaderRoute: typeof DemoQueryableEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoQueryableEventsRoute: DemoQueryableEventsRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
