check:
    quint typecheck util.qnt
    quint typecheck segments.qnt

run:
    quint run segments.qnt --main=tableInsertModel --invariants=inv --backend=rust
    quint run segments.qnt --main=tableReorgModel --invariants=inv --backend=rust

verify:
    quint verify segments.qnt --main=tableInsertModel --invariants=inv
    quint verify segments.qnt --main=tableReorgModel --invariants=inv

debug:
    quint run segments.qnt --main=tableInsertModel --max-steps=5 --invariants=inv --backend=typescript --verbosity=3
