ALTER TABLE file_metadata ADD COLUMN IF NOT EXISTS object_size BIGINT;
ALTER TABLE file_metadata ADD COLUMN IF NOT EXISTS object_e_tag TEXT;
ALTER TABLE file_metadata ADD COLUMN IF NOT EXISTS object_version TEXT;
ALTER TABLE file_metadata ADD COLUMN IF NOT EXISTS num_rows BIGINT DEFAULT -1 NOT NULL;
ALTER TABLE file_metadata ADD COLUMN IF NOT EXISTS size_hint INTEGER DEFAULT -1 NOT NULL;