// This file is @generated by prost-build.
pub mod solana {
    pub mod storage {
        pub mod confirmed_block {
            include!("solana.storage.confirmed_block.rs");
        }
        pub mod entries {
            include!("solana.storage.entries.rs");
        }
        pub mod transaction_by_addr {
            include!("solana.storage.transaction_by_addr.rs");
        }
    }
}
